### PR TITLE
Added PHPUnit to project, and wrote some basic tests for Game class

### PR DESCRIPTION
**Pull request by GregMayes**
I realise it's not much, but I figured it was at least a start in terms of test coverage. 

I created some additional getters in Game to improve testability, as well making a slight change to the __construct method signature.

### CODE REVIEW

**Comment by nebez** [comment]
@GregMayes - this is great stuff! Thanks.
Do you think we should also toss in a travis config to get tests running too?

**Comment by GregMayes** [comment]
Sure, that sounds like a good idea! 

Has Travis been added to the project already? I can add a travis.yml file if you'd like?

**Comment by nebez** [comment]
@GregMayes yeah could you include one in your PR?

**Comment by GregMayes** [comment]
All done. I downgraded the version of PHPUnit to ^6.5 to ensure that it works on PHP7.0 (PHPUnit 7+ requires PHP7.1 and above).

**Comment by nebez** [comment]
Thanks @GregMayes !

**Pull request merged**
